# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# pod install version 1.11.3

target 'NEMODU' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NEMODU
  # Rx
  pod 'RxSwift', '< 6.2.0'
  pod 'RxCocoa', '< 6.2.0'
  pod 'RxGesture', '< 4.1.0'
  pod 'RxDataSources', '<5.1.0'
  
  # Others
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'Then'
  pod 'DynamicBottomSheet'
  pod 'UITextView+Placeholder'
  pod 'lottie-ios'
end
