# Uncomment the next line to define a global platform for your project
  platform :ios, '15.5'

# pod install version 1.11.3

target 'NEMODU' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NEMODU
  # Rx
  pod 'RxSwift', '< 6.2.0'
  pod 'RxCocoa', '< 6.2.0'
  pod 'RxGesture', '< 4.1.0'
  pod 'RxDataSources', '<5.1.0'

  # Kakaotalk
  pod ‘KakaoSDKUser’, '< 2.13.1'
  pod ‘KakaoSDKAuth’, '< 2.13.1'
  
  # Others
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'Then'
  pod 'DynamicBottomSheet'
  pod 'UITextView+Placeholder'
  pod 'lottie-ios'
  pod 'Kingfisher', '~> 7.0'
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
               end
          end
   end
end
